-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 14:50:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Cafe
-- -----------------------------------------------------
-- DeepKit Database Model Project
DROP SCHEMA IF EXISTS `Cafe` ;

-- -----------------------------------------------------
-- Schema Cafe
--
-- DeepKit Database Model Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cafe` DEFAULT CHARACTER SET utf8 ;
USE `Cafe` ;

-- -----------------------------------------------------
-- Table `Cafe`.`меню`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cafe`.`меню` ;

CREATE TABLE IF NOT EXISTS `Cafe`.`меню` (
  `номер` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(255) NOT NULL,
  `статус` TINYINT(1) NOT NULL DEFAULT 0,
  `дополнительно` MEDIUMTEXT NULL COMMENT 'JSON',
  PRIMARY KEY (`номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafe`.`раздел`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cafe`.`раздел` ;

CREATE TABLE IF NOT EXISTS `Cafe`.`раздел` (
  `номер` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(255) NOT NULL,
  `статус` TINYINT(1) NOT NULL DEFAULT 0,
  `описание` TINYTEXT NULL,
  `номер_меню` INT(10) UNSIGNED NOT NULL,
  `дополнительно` MEDIUMTEXT NULL COMMENT 'JSON - props',
  PRIMARY KEY (`номер`),
  INDEX `fk_cafe_sections_cafe_menu1_idx` (`номер_меню` ASC),
  CONSTRAINT `fk_cafe_sections_cafe_menu1`
    FOREIGN KEY (`номер_меню`)
    REFERENCES `Cafe`.`меню` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cafe`.`продукт`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cafe`.`продукт` ;

CREATE TABLE IF NOT EXISTS `Cafe`.`продукт` (
  `номер` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(255) NOT NULL,
  `статус` TINYINT(1) NOT NULL DEFAULT 0,
  `описание` TINYTEXT NULL,
  `номер_раздела` INT(10) UNSIGNED NOT NULL,
  `дополнительно` MEDIUMTEXT NULL COMMENT 'JSON',
  PRIMARY KEY (`номер`),
  INDEX `fk_cafe_product_cafe_sections1_idx` (`номер_раздела` ASC),
  CONSTRAINT `fk_cafe_product_cafe_sections1`
    FOREIGN KEY (`номер_раздела`)
    REFERENCES `Cafe`.`раздел` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
