-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 13:59:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Market
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Market` ;

-- -----------------------------------------------------
-- Schema Market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Market` DEFAULT CHARACTER SET utf8 ;
USE `Market` ;

-- -----------------------------------------------------
-- Table `Market`.`Категории`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Market`.`Категории` ;

CREATE TABLE IF NOT EXISTS `Market`.`Категории` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `наименование` VARCHAR(60) NOT NULL,
  `описание` VARCHAR(160) NULL,
  PRIMARY KEY (`номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`Разделы`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Market`.`Разделы` ;

CREATE TABLE IF NOT EXISTS `Market`.`Разделы` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `наименование` VARCHAR(80) NOT NULL,
  `описание` VARCHAR(160) NULL,
  `номер_категории` INT NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_Разделы_Категории_idx` (`номер_категории` ASC),
  CONSTRAINT `fk_Разделы_Категории`
    FOREIGN KEY (`номер_категории`)
    REFERENCES `Market`.`Категории` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`Товары`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Market`.`Товары` ;

CREATE TABLE IF NOT EXISTS `Market`.`Товары` (
  `артикул` INT NOT NULL,
  `наименование` VARCHAR(160) NOT NULL,
  `стоимость` DECIMAL(7,2) NOT NULL DEFAULT 0,
  `количество` INT(3) NOT NULL DEFAULT 1,
  `описание` TEXT NULL,
  `номер_раздела` INT NOT NULL,
  PRIMARY KEY (`артикул`),
  INDEX `fk_Товары_Разделы1_idx` (`номер_раздела` ASC),
  CONSTRAINT `fk_Товары_Разделы1`
    FOREIGN KEY (`номер_раздела`)
    REFERENCES `Market`.`Разделы` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`Заказы`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Market`.`Заказы` ;

CREATE TABLE IF NOT EXISTS `Market`.`Заказы` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `дата_оформления` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `заказчик` VARCHAR(255) NOT NULL,
  `телефон` VARCHAR(30) NOT NULL,
  `статус` VARCHAR(60) NOT NULL DEFAULT 'Ожидает',
  PRIMARY KEY (`номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`Элементы_заказа`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Market`.`Элементы_заказа` ;

CREATE TABLE IF NOT EXISTS `Market`.`Элементы_заказа` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `количество` INT NOT NULL DEFAULT 1,
  `артикул_товара` INT NOT NULL,
  `номер_заказа` INT NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_Элементы_заказа_Товары1_idx` (`артикул_товара` ASC),
  INDEX `fk_Элементы_заказа_Заказы1_idx` (`номер_заказа` ASC),
  CONSTRAINT `fk_Элементы_заказа_Товары1`
    FOREIGN KEY (`артикул_товара`)
    REFERENCES `Market`.`Товары` (`артикул`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Элементы_заказа_Заказы1`
    FOREIGN KEY (`номер_заказа`)
    REFERENCES `Market`.`Заказы` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
