-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 15:30:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
-- DeepKit Database Model Project
DROP SCHEMA IF EXISTS `Blog` ;

-- -----------------------------------------------------
-- Schema Blog
--
-- DeepKit Database Model Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog` DEFAULT CHARACTER SET utf8 ;
USE `Blog` ;

-- -----------------------------------------------------
-- Table `Blog`.`Категория`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Категория` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Категория` (
  `номер` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `номер_родителя` INT(10) NULL,
  `статус` TINYINT(1) NOT NULL DEFAULT 0,
  `название` VARCHAR(255) NOT NULL,
  `картинка` VARCHAR(255) NULL,
  `описание` TEXT NULL,
  `дополнительно` VARCHAR(255) NULL COMMENT 'JSON - Meta tags',
  PRIMARY KEY (`номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Публикация`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Публикация` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Публикация` (
  `номер` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `номер_автора` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `название` VARCHAR(255) NOT NULL,
  `статус` TINYINT(1) NOT NULL DEFAULT 0,
  `теги` VARCHAR(255) NULL,
  `контент` TEXT NULL,
  `краткое_описание` TINYTEXT NULL,
  `поддержка_комментариев` TINYINT(1) NOT NULL DEFAULT 0,
  `количество_комментариев` INT(10) NOT NULL DEFAULT 0,
  `дата_создания` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `привилегии` VARCHAR(255) NULL,
  `дополнительно` MEDIUMTEXT NULL COMMENT 'JSON - Meta tags',
  `категория` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_blog_post_blog_section1_idx` (`категория` ASC),
  CONSTRAINT `fk_blog_post_blog_section1`
    FOREIGN KEY (`категория`)
    REFERENCES `Blog`.`Категория` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Комментарий`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Комментарий` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Комментарий` (
  `номер` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `номер_родителя` INT(10) NOT NULL DEFAULT 0,
  `номер_публикации` INT(10) UNSIGNED NOT NULL,
  `номер_автора` INT(10) NOT NULL DEFAULT 0,
  `автор` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(255) NOT NULL,
  `дата_создания` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `статус` TINYINT(1) NOT NULL DEFAULT 0,
  `контент` TEXT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_blog_comment_blog_post1_idx` (`номер_публикации` ASC),
  CONSTRAINT `fk_blog_comment_blog_post1`
    FOREIGN KEY (`номер_публикации`)
    REFERENCES `Blog`.`Публикация` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Серия_Публикаций`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog`.`Серия_Публикаций` ;

CREATE TABLE IF NOT EXISTS `Blog`.`Серия_Публикаций` (
  `номер` INT(10) UNSIGNED NOT NULL,
  `название` VARCHAR(255) NOT NULL,
  `описание` VARCHAR(255) NULL,
  `дополнительно` MEDIUMTEXT NULL,
  PRIMARY KEY (`номер`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
