-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 13:59:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema News
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `News` ;

-- -----------------------------------------------------
-- Schema News
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `News` DEFAULT CHARACTER SET utf8 ;
USE `News` ;

-- -----------------------------------------------------
-- Table `News`.`Пользователи`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `News`.`Пользователи` ;

CREATE TABLE IF NOT EXISTS `News`.`Пользователи` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `имя` VARCHAR(60) NOT NULL,
  `фамилия` VARCHAR(60) NOT NULL,
  `почта` VARCHAR(255) NOT NULL,
  `пароль` VARCHAR(255) NOT NULL,
  `дата_регистрации` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`номер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `News`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `News`.`Новости` ;

CREATE TABLE IF NOT EXISTS `News`.`Новости` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `заголовок` VARCHAR(60) NOT NULL,
  `краткое_описание` TEXT NULL,
  `содержимое` TEXT NULL,
  `дата_публикации` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `автор` INT NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_News_Пользователи_idx` (`автор` ASC),
  CONSTRAINT `fk_News_Пользователи`
    FOREIGN KEY (`автор`)
    REFERENCES `News`.`Пользователи` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `News`.`Комментарии`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `News`.`Комментарии` ;

CREATE TABLE IF NOT EXISTS `News`.`Комментарии` (
  `номер` INT NOT NULL AUTO_INCREMENT,
  `заголовок` VARCHAR(30) NOT NULL,
  `текст` VARCHAR(160) NOT NULL,
  `дата_публикации` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `номер_News` INT NOT NULL,
  PRIMARY KEY (`номер`),
  INDEX `fk_Комментарии_News1_idx` (`номер_News` ASC),
  CONSTRAINT `fk_Комментарии_News1`
    FOREIGN KEY (`номер_News`)
    REFERENCES `News`.`News` (`номер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
